### ISSUE TITLE
Problems with rights I guess

### ISSUE THREAD

**Issue by richardaanzee** [harikt/php-hyperclick#2]
When installing on a mac I have a problem with the plugin that i traced back to the following row in getfilepath.php.

`if (file_exists($autoloader)) {`

The file_exists cant handle paths with a space in them.
Also I don't know why but a perfectly working path in the shell is not recognised in this functions.
When I remove the if statement also the require then does not work with the path provided.

So I guess its a rights issues. I want to help debug this but if you have any suggestions please let me know.

**Comment by harikt** [comment]
Hi @richardaanzee ,

Try `echo $autoloader; exit;` after line https://github.com/harikt/php-hyperclick/blob/052d5fd61ea6538aa84fea33db733525530958a7/php/getfilepath.php#L5 . You will get some notification. If you can give the information I can probably suggest some other ways.

If you want to check and make sure it is permission issue change to http://php.net/is_readable function.

PR welcome in case that is the issue.

Thank you.

**Comment by harikt** [comment]
Another way if it is permission issue is `chmod +x getfilepath.php` file.

**Comment by richardaanzee** [comment]
This gives me "-norights-..." back. So i do not have enough rights to execute getfilepath.php.

> <?php
> $class = $argv[1];
> $file = $argv[2];
> $rootpath = $argv[3];
> $autoloader = $rootpath . '/vendor/autoload.php';
> if (!is_readable($autoloader)) {
>   echo "-norights-$autoloader";
> } else {
>   if (file_exists($autoloader)) {
>       $loader = require $autoloader;
> 
> ```
>   require __DIR__ . '/FQCN.php';
> 
>   $contents = file_get_contents($file);
>   $fqns = new Hkt\FQCN();
>   $useClasses = $fqns->getAllUseStatements($contents);
>   if (array_key_exists($class, $useClasses)) {
>       echo $loader->findFile($useClasses[$class]);
>   } else {
>       // Get current namespace
>       $namespace = $fqns->getNamespace();
>       if ($namespace) {
>           $class = $namespace . '\\' . $class;
>       }
>       echo $loader->findFile($class);
>   }
> ```
> 
>   }
> }

I have chmod +x the file.. but no result.

**Comment by harikt** [comment]
> This gives me "-norights-..." back

Do you have composer `vendor/autoload.php` in the root of the project ?

**Comment by richardaanzee** [comment]
Yes I got it.. Simply said I have a project setup with laravel and the application is setup in the directory "app".
Now I opened the directory containing the "app" folder. So it gives me the folder path of the open folder.
Instead of the app folder itself.
You can still try to navigate to a class but php-hyperclick looks for:

/projectfolder/vendor/autoload.php

**Instead of:**

/projectfolder/app/vendor/autoload.php

It is about the determination of what folder the file is opened in that is not really working well yet.
When I opened up the /project/vendor/app directory all works well.

Hopes this helps.

**Comment by harikt** [comment]
Yes, you are correct. It cannot guess where the `vendor/autoload.php` is when you application is nested. ie a know limitation. So closing the issue.

Thank you for trying and using it.

**Comment by richardaanzee** [comment]
Maybe a notification that the plugin cant find the vendor/autoload.php and the path it is searching in might be helpful.

**Comment by harikt** [comment]
True. I will try to address it.

**Comment by harikt** [comment]
@richardaanzee addressed. Let me know if we need to make any changes.

Thank you once again for your valuable feedback.
