### ISSUE TITLE
Work in hack?

### ISSUE THREAD

**Issue by vovanmix** [harikt/php-hyperclick#9]
Is there any way to make it work in Hack? I found that if I just change the opening tag in a php file to `<?hh` it stops working. PHP and Hack have almost the same syntax, maybe it's possible to handle Hack?

**Comment by harikt** [comment]
I am Sorry to say I have not tried or have any plans to make it work on Hack.

~~Aren't there packages nucleus ( something like that I guess ) works for hack ?~~

UPDATE : https://nuclide.io/ what I was suggesting.

**Comment by harikt** [comment]
Thank you for your interest in this.

I don't think this will ever be compatible / work on Hack. Sorry to say so. But as far as I am not working on Hack I can't help with it.

Closing the issue for now.
